name: BeSuperman
main: me.C0nsole.BeSuperman.BeSuperman
version: 2.4
author: C0nsole
commands:
   superman:
     description: Can display info, or change whether you are superman.
     permission: superman.use
permissions:
   superman.use:
     description: Allows the use of /superman
     default: op